#pragma once

enum class TokenType {
  // Single-character tokens
  LEFT_PAREN, RIGHT_PAREN,
  LEFT_BRACE, RIGHT_BRACE,
  LEFT_BRACKET, RIGHT_BRACKET,
  COMMA, DOT, SEMICOLON, COLON,

  // Operators
  PLUS, MINUS, STAR, SLASH, PERCENT,
  EQUAL, BANG, LESS, GREATER,
  AND, OR, XOR, TILDE, QUESTION,

  // Two-character tokens
  PLUS_PLUS, MINUS_MINUS,
  PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL, SLASH_EQUAL, PERCENT_EQUAL,
  AND_EQUAL, OR_EQUAL, XOR_EQUAL,
  EQUAL_EQUAL, NOT_EQUAL,
  LESS_EQUAL, GREATER_EQUAL,
  LEFT_SHIFT, RIGHT_SHIFT,
  AND_AND, OR_OR,
  ARROW, COLON_COLON,

  // Literals
  IDENTIFIER, STRING, CHAR, INTEGER, FLOAT,

  // Keywords
  RETURN, IF, ELSE, WHILE, FOR,
  STRUCT, CLASS, CONST,
  VOID, INT, FLOAT_TYPE, CHAR_TYPE, BOOL,
  TRUE, FALSE, NULLPTR,

  // End of file marker
  END_OF_FILE
};